import type { Car } from "./types"

export const cars: Car[] = [
  {
    id: "1",
    name: "Toyota Camry",
    brand: "Toyota",
    type: "midsize",
    fuelType: "gasoline",
    transmission: "automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 45,
    rating: 4.5,
    reviews: 128,
    image: "/placeholder.svg?height=200&width=300&text=Toyota+Camry+Silver",
    features: ["Air Conditioning", "Bluetooth", "GPS Navigation", "Backup Camera"],
    available: true,
    location: "New York",
  },
  {
    id: "2",
    name: "Honda Civic",
    brand: "Honda",
    type: "compact",
    fuelType: "gasoline",
    transmission: "automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 35,
    rating: 4.3,
    reviews: 95,
    image: "/placeholder.svg?height=200&width=300&text=Honda+Civic+Blue",
    features: ["Air Conditioning", "Bluetooth", "USB Ports"],
    available: true,
    location: "Los Angeles",
  },
  {
    id: "3",
    name: "BMW X5",
    brand: "BMW",
    type: "luxury",
    fuelType: "gasoline",
    transmission: "automatic",
    seats: 7,
    doors: 4,
    pricePerDay: 95,
    rating: 4.8,
    reviews: 67,
    image: "/placeholder.svg?height=200&width=300&text=BMW+X5+Black+Luxury+SUV",
    features: ["Leather Seats", "Sunroof", "Premium Audio", "GPS Navigation", "Heated Seats"],
    available: true,
    location: "Miami",
  },
  {
    id: "4",
    name: "Tesla Model 3",
    brand: "Tesla",
    type: "luxury",
    fuelType: "electric",
    transmission: "automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 75,
    rating: 4.7,
    reviews: 89,
    image: "/placeholder.svg?height=200&width=300&text=Tesla+Model+3+White+Electric",
    features: ["Autopilot", "Premium Audio", "Glass Roof", "Supercharging"],
    available: true,
    location: "San Francisco",
  },
  {
    id: "5",
    name: "Ford Explorer",
    brand: "Ford",
    type: "suv",
    fuelType: "gasoline",
    transmission: "automatic",
    seats: 7,
    doors: 4,
    pricePerDay: 65,
    rating: 4.4,
    reviews: 112,
    image: "/placeholder.svg?height=200&width=300&text=Ford+Explorer+Red+SUV",
    features: ["3rd Row Seating", "Towing Package", "All-Wheel Drive", "Bluetooth"],
    available: true,
    location: "Chicago",
  },
  {
    id: "6",
    name: "Nissan Altima",
    brand: "Nissan",
    type: "midsize",
    fuelType: "gasoline",
    transmission: "automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 40,
    rating: 4.2,
    reviews: 76,
    image: "/placeholder.svg?height=200&width=300&text=Nissan+Altima+Gray+Sedan",
    features: ["Air Conditioning", "Bluetooth", "Backup Camera", "Keyless Entry"],
    available: true,
    location: "Dallas",
  },
]

export const locations = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "Fort Worth",
  "Columbus",
  "Charlotte",
  "San Francisco",
  "Indianapolis",
  "Seattle",
  "Denver",
  "Washington DC",
  "Boston",
  "El Paso",
  "Nashville",
  "Detroit",
  "Oklahoma City",
  "Portland",
  "Las Vegas",
  "Memphis",
  "Louisville",
  "Baltimore",
  "Milwaukee",
  "Albuquerque",
  "Tucson",
  "Fresno",
  "Sacramento",
  "Kansas City",
  "Mesa",
  "Atlanta",
  "Omaha",
  "Colorado Springs",
  "Raleigh",
  "Miami",
  "Virginia Beach",
  "Oakland",
  "Minneapolis",
  "Tulsa",
  "Arlington",
  "Tampa",
  "New Orleans",
  "Wichita",
  "Cleveland",
]
